/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "梦想远方",
  "description": "诗和远方",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-32946c91",
      "path": "/",
      "lastUpdated": "6/6/2022, 9:56:19 PM",
      "lastUpdatedTimestamp": 1654523779000
    },
    {
      "frontmatter": {},
      "regularPath": "/css/BFC.html",
      "relativePath": "css/BFC.md",
      "key": "v-ae01ab86",
      "path": "/css/BFC.html",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-0b836d16",
      "path": "/css/",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "frontmatter": {},
      "regularPath": "/http/http&https.html",
      "relativePath": "http/http&https.md",
      "key": "v-a0ad29d2",
      "path": "/http/http&https.html",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "title": "HTTP 知识",
      "frontmatter": {},
      "regularPath": "/http/",
      "relativePath": "http/README.md",
      "key": "v-5a973198",
      "path": "/http/",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "frontmatter": {},
      "regularPath": "/css/css.html",
      "relativePath": "css/css.md",
      "key": "v-48481686",
      "path": "/css/css.html",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "title": "Promise",
      "frontmatter": {},
      "regularPath": "/js/Promise.html",
      "relativePath": "js/Promise.md",
      "key": "v-49dc4599",
      "path": "/js/Promise.html",
      "headers": [
        {
          "level": 3,
          "title": "Promise",
          "slug": "promise"
        }
      ]
    },
    {
      "title": "JavaScript",
      "frontmatter": {},
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-0eb31b14",
      "path": "/js/",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "title": "JS 检测方法",
      "frontmatter": {
        "title": "JS 检测方法"
      },
      "regularPath": "/js/DetectionMethod.html",
      "relativePath": "js/DetectionMethod.md",
      "key": "v-25685343",
      "path": "/js/DetectionMethod.html",
      "headers": [
        {
          "level": 3,
          "title": "JS 检测方法",
          "slug": "js-检测方法"
        }
      ],
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "title": "JS 异步发展历程",
      "frontmatter": {
        "title": "JS 异步发展历程"
      },
      "regularPath": "/js/asyncDevelop.html",
      "relativePath": "js/asyncDevelop.md",
      "key": "v-785496b7",
      "path": "/js/asyncDevelop.html",
      "headers": [
        {
          "level": 3,
          "title": "JS 异步发展历程",
          "slug": "js-异步发展历程"
        }
      ]
    },
    {
      "title": "var、let、cosnt的区别",
      "frontmatter": {
        "title": "var、let、cosnt的区别",
        "date": "2022-08-08 22:01"
      },
      "regularPath": "/js/var&let&const.html",
      "relativePath": "js/var&let&const.md",
      "key": "v-95f36ec6",
      "path": "/js/var&let&const.html",
      "headers": [
        {
          "level": 3,
          "title": "var、let、const 的区别",
          "slug": "var、let、const-的区别"
        }
      ],
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    },
    {
      "frontmatter": {},
      "regularPath": "/ts/TS.html",
      "relativePath": "ts/TS.md",
      "key": "v-34788e12",
      "path": "/ts/TS.html",
      "lastUpdated": "6/6/2022, 9:56:19 PM",
      "lastUpdatedTimestamp": 1654523779000
    },
    {
      "title": "typeScript",
      "frontmatter": {},
      "regularPath": "/ts/",
      "relativePath": "ts/README.md",
      "key": "v-43342958",
      "path": "/ts/",
      "lastUpdated": "8/8/2022, 10:11:39 PM",
      "lastUpdatedTimestamp": 1659967899000
    }
  ],
  "themeConfig": {
    "lastUpdated": "上次更新",
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "JS",
        "link": "/js/"
      },
      {
        "text": "CSS",
        "link": "/css/"
      },
      {
        "text": "TS",
        "link": "/ts/"
      },
      {
        "text": "HTTP",
        "link": "/http/"
      }
    ],
    "sidebar": {
      "/css/": [
        {
          "title": "CSS",
          "path": "/css/",
          "children": [
            {
              "title": "css",
              "path": "css"
            },
            {
              "title": "BFC",
              "path": "BFC"
            }
          ]
        }
      ],
      "/js/": [
        {
          "title": "JavaScript",
          "path": "/js/",
          "children": [
            {
              "title": "JS 检测方法",
              "path": "DetectionMethod"
            },
            {
              "title": "var let const的区别",
              "path": "var&let&const"
            },
            {
              "title": "Promise",
              "path": "Promise"
            },
            {
              "title": "JS 异步发展历程",
              "path": "asyncDevelop"
            }
          ]
        }
      ],
      "/ts/": [
        {
          "title": "typeScript",
          "path": "/ts/",
          "children": [
            {
              "title": "ts",
              "path": "TS"
            }
          ]
        }
      ],
      "/http/": [
        {
          "title": "HTTP",
          "path": "/http/",
          "children": [
            {
              "title": "http",
              "path": "http&https"
            }
          ]
        }
      ]
    }
  }
}