/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "梦想远方",
  "description": "诗和远方",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-32946c91",
      "path": "/",
      "lastUpdated": "5/30/2022, 9:20:56 PM",
      "lastUpdatedTimestamp": 1653916856000
    },
    {
      "title": "css",
      "frontmatter": {},
      "regularPath": "/css/css.html",
      "relativePath": "css/css.md",
      "key": "v-48481686",
      "path": "/css/css.html",
      "headers": [
        {
          "level": 2,
          "title": "css",
          "slug": "css"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/ts/TS.html",
      "relativePath": "ts/TS.md",
      "key": "v-34788e12",
      "path": "/ts/TS.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/js/JS.html",
      "relativePath": "js/JS.md",
      "key": "v-718c80f7",
      "path": "/js/JS.html"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "JS",
        "link": "/js/JS"
      },
      {
        "text": "CSS",
        "link": "/css/css"
      },
      {
        "text": "TS",
        "link": "/ts/TS"
      }
    ],
    "sidebar": "auto",
    "lastUpdated": "Last Updated"
  }
}